### ISSUE TITLE
Alternative Database Resource

### ISSUE THREAD

**Issue by Legonois** [kddresearch/KDD-Wiki-NextJS#11]
# User Story
As a Admin Host, I would like to lower the cost of a PostgreSQL database hosted on Azure (North US Central)

## Description
Migrate from the current CosmosDB setup to a cheaper setup that only charges based on the amount of requests we use

### Specs
- Less than $13.50 per month when running idle
- Uses PostgreSQL

## Tasks
- [x] Create list of Azure database resources and estimated costs
- [x] Create database resource
- [x] Dump CosmosDB entries
- [x] Push entries to new database
- [x] Test with Local wiki
- [x] Test with Production wiki
- [x] Compare speeds
- [x] Compare price per day (after a few days of using it)
- [x] Review Pricing with Team (And Dr. Hsu)
- [x] Remove CosmosDB resource

**Comment by Legonois** [comment]
Completed the transition to Azure Database for PostgreSQL flexible server!
