### ISSUE TITLE
Serve files from Blob Containers

### ISSUE THREAD

**Issue by Legonois** [kddresearch/KDD-Wiki-NextJS#12]
# User Story
As a User, I would like to be able to view files that are stored on a Azure Blob Server

## Description
We need to be able to view files that are stored on azure

## Tasks
- [x] Create blob container
- [x] Secure blob container so that only Admins can view files
- [x] Add to public API route

**Comment by Legonois** [comment]
Cannot access the file at api/file/testfile.txt.txt on deployed build, looking into it

**Comment by Legonois** [comment]
Completed! Added a VPN on Azure to connect the storage account, and the app service
