### ISSUE TITLE
Design Page Epic

### ISSUE THREAD

**Issue by Legonois** [kddresearch/KDD-Wiki-NextJS#16]
# User Story

As a Developer, I want to be able to organize and track the progress on the Page system as a collection of User Stories

## Description

We need to design the implementation for the Pages system in the new Wiki

## Tasks

- [x] Design Page object
- [x] Create User stories
- [x] Get feature feedback

**Comment by Legonois** [comment]
## Page Design

### Requirements

Versioning
Access Levels (Authorization)
Sorting how the pages show up in navigation

### Page object

Id
- Int
- Primary Key

Title
- String
- Displays in the text

Name
- String
- Displays in the URL

Author Id
- int (foreign key)
- Original Creator of the page

Access Level
- String (enum)
- Who is able to **view** the page
- Access Levels
  - Guest (not signed in)
  - KSU (signed in)
  - Admin (Only Admins)

Priority
- int
- How the pages would be sorted within the category navigation
- Higher priority, the front of the list

Content
- String
- MDX Content of the page that gets displayed

**Comment by Legonois** [comment]
#User Stories

## Frontend

- ###
- 

## Backend

- ###
- ###
- ###
- ###
- ###

###
