### ISSUE TITLE
Solve VPN Costs

### ISSUE THREAD

**Issue by Legonois** [kddresearch/KDD-Wiki-NextJS#18]
# User Story
As a maintainer, the VPN on azure is way too expensive. I need a network between all the services to not expose the storage container to the internet. 

## Description
Connect all the azure services together through a network while reducing cost

## Tasks
- [x] Delete VPN
- [x] Create Virtual Network
- [x] Connect Storage Account
- [x] Connect Database
- [x] Test production
- [x] Test connection from on premises device

**Comment by Legonois** [comment]
Looking for alternatives, as creating an isolated environment while allowing development versions to connect to it is complicated and tiring me out. That is the goal tho. Air-gapped environments while still being able to manage them

I am looking into [devtest-labs](https://azure.microsoft.com/en-us/products/devtest-lab) by azure for spinning up development specific services when needed.

**Comment by Legonois** [comment]
We are now using a fully managed VNet, with a ssh tunnel to connect to our vnet and resources! Woohoo! All it costs is a 3 dollar per month vm running in the cloud for tunneling. 

Our self hosted runners also run on the same network, so that all db connection testing happens in a almost production environment
