### ISSUE TITLE
Page Categories

### ISSUE THREAD

**Issue by Legonois** [kddresearch/KDD-Wiki-NextJS#20]
# User Story
As an Admin, I want to create and manage categories so that I can organize the directory structure.

## Criteria
- Admins can create, edit, and delete categories
- Categories can contain subcategories and references to pages
- Changes to categories are reflected in the navigation structure

## Tasks
- [ ] Design category schema
- [ ] Create category API endpoint
- [ ] Admin interface for categories
- [ ] Fetch and display categories
- [ ] Write Postman tests for categories

**Comment by Legonois** [comment]
# Category Schema

## Criteria

Contains static pages
Contains more category objects
Implements an ORM (Drizzle ORM)

**Comment by Legonois** [comment]
## ISSUES: 
I hate this part because it means I cannot find a solution online AHHHHHHH
### Top level awaits in NextJS not working
```
The generated code contains 'async/await' because this module is using "topLevelAwait".
However, your target environment does not appear to support 'async/await'.
As a result, the code may not run as expected or may cause runtime errors.
```

been stuck on this for a few hours. I mainly need it in client components. But, turns out you can't have async in client components without a state changer (use effect), so what I am using it for specifically would not work. So, DO NOT USE async at top level in client components without state changes

**Comment by Legonois** [comment]
When implementing the new secrets retreval system, I thought that it would eventually take longer because these routes would reload the config often. But with the singleton, we look to be good! I visited all the routes and it only did 3 reloads!

![Image](https://github.com/kddresearch/KDD-Wiki-NextJS/assets/74224353/fd4c3494-e00b-4222-aeed-4d7056bfaaa5)

I am glad this is working so well
