### ISSUE TITLE
Migrate DB to Drizzle ORM

### ISSUE THREAD

**Issue by Tatenda-k** [kddresearch/KDD-Wiki-NextJS#22]
# User Story
As a Developer, I would like to use Drizzle ORM to replace our current DB solution

## Description
We need to integrate Drizzle and the tools for it into the current wiki

### Requirements
Keep DB functions a single query, and make sure the return the object as a class

### Documentation
[Drizzle ORM](https://orm.drizzle.team/docs/overview)

## Tasks
- [x] Make sure tools are installed
- [x] Connect to DB using drizzle 
- [ ] Migrate current queries from drizzle
- [ ] Review
