### ISSUE TITLE
Migrate to Chadcn/ui

### ISSUE THREAD

**Issue by Legonois** [kddresearch/KDD-Wiki-NextJS#23]
# User Story
As a developer, I would like to be consistent in how the UI looks, and to allow for more customization

## Description

[Chadcn/ui](https://ui.shadcn.com/)
Remove all instances of MUI in the current codebase, and replace all components with Chadcn/ui.

When running install scripts **USE PNPM** otherwise components will not install correctly!

### Example:
```bash
pnpm dlx shadcn-ui@latest add button
```

## Tasks
- [x] Find instances where MUI is being used
- [x] Find/Build equivalents using Chadcn/ui 
- [x] Remove MUI from the codebase
