### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by Legonois** [kddresearch/KDD-Wiki-NextJS#25]
# User Story
As a User, I would like a dynamic navigation system for pages, so that I may add pages and it be reflected in the nav menu

## Description
We need to make tables and page objects in the database, and use that tree functionality to build the ui 

## Tasks
- [ ] Fix URL
- [ ] Migrate to Drizzle ORM
- [ ] Show full parent directory in side nav menu
- [ ] SSR the Nav Bar
