### ISSUE TITLE
Move Config System to Main Branch

### ISSUE THREAD

**Issue by Legonois** [kddresearch/KDD-Wiki-NextJS#27]
# User Story
As a developer, I would like the config file to be using azure secrets.

## Description
We need to migrate the config system off the page editing system 

## Tasks
- [x] Make new branch
- [ ] Copy and paste key store system
- [ ] Run with secrets
