### ISSUE TITLE
Page Tags

### ISSUE THREAD

**Issue by Legonois** [kddresearch/KDD-Wiki-NextJS#28]
# User Story
As a User, tagging is an important system to connect similar pages together.

## Description
Implement a tagging system for pages, such as a page having a "Deep Learning" and "NLP" Tag at the same time.

## Specifications
Created on a separate table
Work with pages with a foreign key reference

## Tasks
- [ ] Design the database schema for tags and the relationship between tags and pages.
- [ ] Use `Drizzle Migrate` to add the table to the DB
- [ ] Create API endpoints for adding, removing, and querying tags.
- [ ] Add Tag UI to pages, with Chadcn/ui
