### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by Legonois** [kddresearch/KDD-Wiki-NextJS#4]
# User Story
As a User, I want to be able to view the source code of a Research Project.

## Description
We need to be able to store the links to the source code

## Tasks
- [ ] Design (Source Code) Object
- [ ] Create Model and Validation
- [ ] Create Table
- [ ] Define Backend
- [ ] Add to Research Project Frontend
- [ ] Define/Do Testing
- [ ] talk to Dr. hsu
