### ISSUE TITLE
Source Code Privacy

### ISSUE THREAD

**Issue by Legonois** [kddresearch/KDD-Wiki-NextJS#5]
# User Story
As an Admin, I want to be able to manage the privacy of the source code of a Research Project.

## Description
We need to be able to manage the privacy of the links to the Source Code

## Tasks
- [ ] Design (Source Code) Object with ownership and privacy
- [ ] Update Model and Validation
- [ ] Update Table
- [ ] Define Backend
- [ ] Add to Research Project Frontend
- [ ] Define/Do Testing
