### ISSUE TITLE
Docker Container Registry

### ISSUE THREAD

**Issue by Legonois** [kddresearch/KDD-Wiki-NextJS#6]
# User Story
As a Admin Host, I would like to be able to publish builds to a private docker container for the cheapest amount possible for deployment

## Description
We need to find a docker registry that integrates well with Github Actions and have authorization/authentication to keep the builds private

### Specs
- Has at least 15 GBs of storage
- Allows downloads from outside of their platform
- Is cheap (Under $10 dollars per month)
- Has a good reputation
- Is able to serve privately (With authentication and authorization)
- Integrates well with Azure

## Tasks
- [x] Create List of Docker Registry Options - @Legonois 
- [x] Create container resource under KDD Org
- [x] Push a container build to the registry
- [x] Pull container build from the registry
- [x] Run container and confirm it works well
- [x] Review Pricing with Team (And Dr. Hsu)
- [x] Integrate with Azure
- [x] Deploy to main WebApp

**Comment by Legonois** [comment]
# Picking Docker container registries 

## Candidates 

### Docker Hub - [Pricing](https://www.docker.com/pricing/)
- Pros
- Can be accessed by Github Actions
  - 5k Image pulls per day
  - Unlimited Private Repositories
  - Costs 5 dollars per month for pro user
- Cons
  - Uses personal account, no easy organization level access and management
  - For organization access and management it's 9 dollars per user per month

### Github Container Registry - [Pricing](https://docs.github.com/en/billing/managing-billing-for-github-packages/about-billing-for-github-packages#about-billing-for-github-packages)
- Pros
  - Integrated directly with Github Actions
  - Easy organization level access
- Cons
  - Only 1 GB of free download transfer (Unless from Github Action)
  - Only 500 MBs of free storage (The container is around 1GB)

### Azure Container Registry - [Pricing](https://azure.microsoft.com/en-us/pricing/details/container-registry/)
- Pros
  - Easy organization level access
  - Can be accessed by Github Actions
  - Base 10GBs
  - $5.177 per month
  - $0.103 per month per extra GB (50 GBs for 5.177 per month)
  - $10.354 per month total (60 GBs size)
- Cons
  - Costs money

## Selected Candidate

### [Azure Container Registry](https://azure.microsoft.com/en-us/products/container-registry#pricing)
- Easy organization level access
- at $10.354 per month
- Works directly with Github Actions

**Comment by Legonois** [comment]
# ISSUES with the freaking Github Actions:

## buildx failed dial tcp: lookup *** no such host

```bash
ERROR: failed to solve: failed to push ***/kdd-***:latest: failed to do request: Head "https://***/v2/kdd-***/blobs/sha256:1f459c0c43b126386259daf94224712861e903434fa7c5a6d2383331db513afc": dial tcp: lookup *** on 168.63.129.16:53: no such host
```

I SPENT HOURS DEBUGGING THIS and it drove me insane (not like I wasn't insane anyways)

## Solved by new workflow
- Using Google DNS
```yaml
- name: Setup Google DNS
      run: |
         echo "nameserver 8.8.8.8" |  sudo tee  /etc/resolv.conf.DNSoverride
         sudo ln -sf /etc/resolv.conf.DNSoverride /etc/resolv.conf
         cat /etc/resolv.conf
```
- adding the registry to the hosts folder
```yaml
    - name: Lookup Registry IP
      id: lookup_ip
      run: |
        REGISTRY_IP=$(nslookup ${{ secrets.CONTAINERREGISTRY }} | grep Address | tail -n 1 | awk '{print $2}')
        echo "REGISTRY_IP=$REGISTRY_IP" >> $GITHUB_ENV
    
    - name: Modify /etc/hosts
      run: |
        echo "${{ env.REGISTRY_IP }} ${{ secrets.CONTAINERREGISTRY }}" | sudo tee -a /etc/hosts
        cat /etc/hosts

    - name: Restart Docker
      run: sudo systemctl restart docker

    - name: Log in to registry
      uses: docker/login-action@v3
      with: 
        registry: ${{ secrets.CONTAINERREGISTRY }}
        username: ${{ secrets.CONTAINERREGISTRYUSERNAME }}
        password: ${{ secrets.CONTAINERREGISTRYPASSWORD }}
```
- Adding the registry domain to the tag
```yaml
    - name: Build and push container image to registry
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.CONTAINERREGISTRY }}/${{ secrets.CONTAINERREGISTRYUSERNAME }}/kdd-wiki:latest
        file: ./Dockerfile
        builder: mybuilder
        network: host
```

Solution: Never use private repos lol

Anyways the production build of the website works with a cheap container build, so starting the pull request with main
