### ISSUE TITLE
Design Research Projects Epic

### ISSUE THREAD

**Issue by Legonois** [kddresearch/KDD-Wiki-NextJS#8]
# User Story
As a Developer, I want to be able to organize and track the progress on the Research Projects system as a collection of User Stories

## Description
We need to be able to take feedback and fully define the system that we will use to create Research Projects and User Stories

## Tasks
- [x] Design (Research Projects) object
- [ ] Review (Research Projects) object
- [ ] Create user stories
- [ ] Get feature feedback on user stories
- [ ] Review with team

**Comment by Legonois** [comment]
##

## JSON

##

##

**Comment by Legonois** [comment]
Things we discussed:

[Navigation Whiteboard](https://excalidraw.com/#json=I-mcU6T5WiAbZ1fwJRq6W,Ma0Cp0O235M35VEtlLqp5Q)

How navigation will work!
I think we came to the conclusion of creating a few things.

I will also be lowering the scope of this project item. This will SOLEY be about the research project design work, not including the implementation side of it. Hopefully will be easier to digest and we can get though this faster

**Comment by Legonois** [comment]
Removed 
~~- [ ] Review with Dr. Hsu~~
~~- [ ] Create issues based on user stories~~
~~- [ ] Review (Research Projects) object~~
~~- [ ] Look into https://github.com/typeorm/typeorm for table creation~~
~~- [ ] Create Research Projects table~~

**Comment by Legonois** [comment]
## User Stories

## Backend

- Design Research Project Dependencies
- 
- Create Research Projects Object
- Design Category Object
- Create Category Object
- Navigation System
- 



## Frontend

- Navigation Bar
- Display Page
